name: "Test with pre/post step"
description: "Test with pre/post step"

inputs:
  pre:
    description: "Run pre step?"
    required: true
  post:
    description: "Run post step?"
    required: true

runs:
  using: "node16"
  main: "main.js"
  pre: "pre.js"
  pre-if: "${{ inputs.pre == 'true' }}"
  post: "post.js"
  post-if: "${{ inputs.post == 'true' }}"
